# Generated by Django 3.2.20 on 2023-08-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230817_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
