# Generated by Django 3.2.20 on 2023-08-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_name_employee_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='attendance_code',
            field=models.CharField(choices=[('AW', 'At Work'), ('OL', 'On Leave')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='time_code',
            field=models.CharField(choices=[('ST', 'Short Time'), ('NT', 'Normal Time'), ('OT', 'Overtime')], max_length=20),
        ),
    ]
