# Generated by Django 3.2.20 on 2023-08-18 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_employee_time_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_number',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='attendance_code',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='clocked_in',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='clocked_out',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='shift_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='time_approved',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='time_code',
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='occupation',
            field=models.CharField(blank=True, default='Unspecified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
