# Generated by Django 3.2.20 on 2023-08-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_employee_id_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='occupation',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('IT', 'IT'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('HR', 'Human Resources')], max_length=100, null=True),
        ),
    ]
