# Generated by Django 3.2.20 on 2023-08-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20230820_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('IT', 'IT'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('HR', 'Human Resources')], default='Sales', max_length=100, null=True),
        ),
    ]
