# Generated by Django 3.2.20 on 2023-08-20 23:28

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20230821_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='attendance_code',
            field=models.CharField(choices=[('AW', 'At Work'), ('OL', 'On Leave')], default='AW', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='time_authorized',
            field=models.TimeField(blank=True, default=main.models.default_time, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='time_code',
            field=models.CharField(choices=[('ST', 'Short Time'), ('NT', 'Normal Time'), ('OT', 'Overtime')], default='NT', max_length=20),
        ),
    ]
