# Generated by Django 3.2.20 on 2023-08-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20230821_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='attendance_code',
            field=models.CharField(choices=[('AW', 'At Work'), ('OL', 'On Leave')], default='AW', max_length=2),
        ),
        migrations.AddField(
            model_name='employee',
            name='clocked_in',
            field=models.TimeField(default='00:00', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='clocked_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('IT', 'IT'), ('S', 'Sales'), ('MRKT', 'Marketing'), ('HR', 'Human Resources')], default='S', max_length=4),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_date',
            field=models.DateField(default='2023-08-01'),
        ),
        migrations.AddField(
            model_name='employee',
            name='time_authorized',
            field=models.TimeField(blank=True, default='00:00', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='time_code',
            field=models.CharField(choices=[('ST', 'Short Time'), ('NT', 'Normal Time'), ('OT', 'Overtime')], default='NT', max_length=3),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
